### ISSUE TITLE
vCenter: privileg check failed for user (missing permission Sessions.TerminateSession

### ISSUE THREAD

**Issue by quinh** [sexibytes/sexigraf#341] opened 2023-04-05 09:22 UTC
Hi,

first things first: great product, easy to use, little efffort, big outcome :+1: 

`Privilege check failed for user VSPHERE.LOCAL\sexigraf for missing permission Sessions.TerminateSession. Session user performing the check: VSPHERE.LOCAL\sexigraf `

We configured only ~~view~~ read-only permissions for user sexigraf.

The **sessions** object only have 4 [permissions available](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-84BDB0C4-AAB8-41AA-BB52-66C5E2A5B5A1.html)
- Impersonate User
- Message
- Validate session
- View and Stop sessions 

Any clue what's behind VMwares warning: `Sessions.TerminateSession` ?

**Comment by rschitz** [comment] 2023-04-05 09:26
Hi and thank you for your support.
Read-Only Role is enough but where (on which object) did you applied this permission?

**Comment by rschitz** [comment] 2023-04-05 09:32
can you share a screenshot of the warning please?

**Comment by rschitz** [comment] 2023-04-05 09:35
i'm sorry i didn't see you set view permission, please switch to read-only with propagate to children enabled
<img width="403" alt="image" src="https://user-images.githubusercontent.com/8385646/230042108-fbd0e32f-6203-46bd-8b29-bfba669fc17a.png">

**Comment by quinh** [comment] 2023-04-05 09:45
Sorry for the confusion, i did't know "view" existed. We're using Role "read-only" forever.

**Comment by rschitz** [comment] 2023-04-05 09:51
it looks like we are not the only one suffering from this issue: https://forum.xorux.com/discussion/1098/vmware-permission-errors

**Comment by quinh** [comment] 2023-04-05 09:53
> can you share a screenshot of the warning please?

![sexigraf](https://user-images.githubusercontent.com/2214259/230046805-2a5aaa5b-4e9d-456b-8e94-2035fe0700e8.png)

**Comment by quinh** [comment] 2023-04-05 09:55
> it looks like we are not the only one suffering from this issue: https://forum.xorux.com/discussion/1098/vmware-permission-errors

Mhm, we're going to upgrade our vcenters later in april. I will respond here, if this error is eleminated by the update or not if you like.

**Comment by rschitz** [comment] 2023-04-05 09:59
i'm discovering that i've already commented the code with this issue but impossible to remember why...
https://github.com/sexibytes/sexigraf/blob/develop/opt/sexigraf/ViPullStatistics.ps1#L275
i'll dig into it, fell free to update this issue whenever you like of course and again thank you for your help and feedback.

**Comment by quinh** [comment] 2023-04-05 12:08
Out of curiosity we've cloned the read-only role and added the session: view and stop sessions

![custom_role](https://user-images.githubusercontent.com/2214259/230075576-b004a1ce-4404-4d81-b1d8-0bf68a7b1631.png)

And to no suprise, the warning does not appear again.

**Comment by rschitz** [comment] 2023-04-05 12:09
Great, thanks. Actually this is for session listing so i'll add a permission check as a condition for that part

**Comment by quinh** [comment] 2023-04-05 12:26
Ah, no it's getting clearer. Look at the VMware vCenter active sessions dashboard. The timespan when we changed the role  to have the "view and stop sessions" permission delivered actual data. Afterwards we switched back to "read-only" and it stopped again.

![active_sessions_dashboard](https://user-images.githubusercontent.com/2214259/230079960-f90ffa9c-be84-44f0-91b0-0c73c19ec0a7.png)

**Comment by rschitz** [comment] 2023-04-05 12:28
yes the permission has been changed a long time ago

**Comment by rschitz** [comment] 2023-04-06 12:00
@quinh feel free to test the fixed code i just comited. i'll close this issue now that the problem is fixed, thank you very much for your support!

**Comment by quinh** [comment] 2023-04-18 08:55
@rschitz  - back from vacation and testing your fixes.

sexigraf logfile says:
`[INFO] Sessions.TerminateSession privilege not detected, SessionManager skipped ...  `

but vCenter still says:
`Privilege check failed for user VSPHERE.LOCAL\Sexygraf for missing permission Sessions.TerminateSession. Session user performing the check: VSPHERE.LOCAL\Sexygraf`

**Comment by rschitz** [comment] 2023-04-19 22:56
Please try this version, for some weird reasons, checking permissions triggers the alert so i worked around this by getting the privileges from the role of the user. After modifying the ps1 file, please terminate the sexigraf user session because i also noticed that connecting with a previous token after changing the permission could also trigger the alert.

![image](https://user-images.githubusercontent.com/8385646/233217185-9be0933f-e04e-4631-bfce-9ec58aa4dae6.png)

**Closed** 2023-07-23 15:39 UTC
Labels: enhancement
